    <nav id="menu-h">
        <ul>
            <li><a href="../menu/clients.php">Clientes</a></li>
            <li><a href="../menu/products.php">Produtos</a></li>            
            <li><a href="../menu/providers.php">Fornecedores</a></li>            
            <li><a href="../menu/professionals.php">Funcionários</a></li>
            <li><a href="../menu/users.php">Usuários</a>
            <li><a href="#">Vendas</a></li>
            <div class="dropdown">
                <li>
                <a>Consultas</a>
                <div class="dropdown-content">
                    <a href="../search/search-client.php">Clientes</a>
                    <a href="../search/search-product.php">Produtos</a>
                    <a href="../search/search-provider.php">Fornecedores</a>
                    <a href="../search/search-professional.php">Funcionários</a>
                    <a href="../search/search-user.php">Usuários</a>
                </div>
                </li>
            </div>
            <li><a href="#">Configurações</a></li>
            <li><a href="login/logout.php">Sair</a></li>
        </ul>
    </nav>
