    <nav id="menu-h">
        <ul>
            <li><a href="cadastro.php">Clientes</a></li>
            <li><a href="#">Produtos</a></li>            
            <li><a href="#">Fornecedores</a></li>            
            <li><a href="#">Funcionários</a></li>
            <li><a href="#">Usuários</a></li>
            <li><a href="#">Vendas</a></li>
            <li><a href="#">Relatórios</a></li>
            <li><a href="#">Configurações</a></li>
            <li><a href="login/logout.php">Sair</a></li>
        </ul>
    </nav>
