    <nav id="menu-h">
        <ul>
            <li><a href="../menu/clients.php">Clientes</a></li>
            <li><a href="../menu/products.php">Produtos</a></li>            
            <li><a href="../menu/providers.php">Fornecedores</a></li>            
            <li><a href="../menu/professionals.php">Funcionários</a></li>
            <li><a href="../menu/users.php">Usuários</a></li>
            <li><a href="#">Vendas</a></li>
            <li><a href="#">Relatórios</a></li>
            <li><a href="#">Configurações</a></li>
            <li><a href="login/logout.php">Sair</a></li>
        </ul>
    </nav>
